# 最小推拉流：RTMP 推入 → HLS 拉出
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        off;

http_server {
    enabled         on;
    listen          8080;
    crossdomain     on;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_fragment    2;
        hls_window      10;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}
